UploadFile: Add support for 0x0.st

diff --git a/UploadFile/source/uploadfile b/UploadFile/source/uploadfile
--- a/UploadFile/source/uploadfile
+++ b/UploadFile/source/uploadfile
@@ -50,17 +50,24 @@ function transfer {
   echo -n "${file_name}" > "${name_file}"
   notification "Uploading “${file_name}”"
 
-  readonly hosts=('transfer.sh' 'alpha.transfer.sh' 'bayfiles.com' 'anonfile.com' 'megaupload.is' 'forumfiles.com')
+  readonly hosts=('0x0.st' 'transfer.sh' 'alpha.transfer.sh' 'bayfiles.com' 'anonfile.com' 'megaupload.is' 'forumfiles.com')
   readonly default_host="${hosts[0]}"
 
-  if [[ -n "${upload_file_to}" ]] && string_in_array "${upload_file_to}" "${hosts[@]}"; then
-    upload_host="${upload_file_to}"
+  if [[ -n "${upload_file_to}" ]]; then
+    if string_in_array "${upload_file_to}" "${hosts[@]}"; then
+      readonly upload_host="${upload_file_to}"
+    else
+      echo "Invalid upload host: ${upload_file_to}" >&2
+      exit 1
+    fi
   else
-    upload_host="${default_host}"
+    readonly upload_host="${default_host}"
   fi
 
   if [[ "${upload_host}" =~ ^(alpha\.)?transfer\.sh$ ]]; then
     curl --globoff --progress-bar --upload-file "${file_path}" "https://${upload_host}/${file_name}" 2> "${progress_file}" | tr -d '\n' | pbcopy
+  elif [[ "${upload_host}" == '0x0.st' ]]; then
+    curl --globoff --progress-bar --form "file=@${file_path}" "https://${upload_host}" 2> "${progress_file}" | tr -d '\n' | pbcopy
   else
     curl --globoff --progress-bar --form "file=@${file_path}" "https://api.${upload_host}/upload" 2> "${progress_file}" | ruby -e 'require "json"; data = JSON.parse(gets); abort "There was an error uploading" if data["status"] == false; puts data["data"]["file"]["url"]["full"]' | tr -d '\n' | pbcopy
   fi
