UploadFile: Temp dir cleanup and handling software bundles

diff --git a/UploadFile/source/uploadfile b/UploadFile/source/uploadfile
--- a/UploadFile/source/uploadfile
+++ b/UploadFile/source/uploadfile
@@ -1,7 +1,12 @@
 #!/bin/bash
 
+# Create and cleanup temporary paths
 readonly progress_file='/tmp/uploadfile_progress'
 readonly name_file='/tmp/uploadfile_name' # for `ufp` (in Alfred)
+readonly tmp_dir="$(mktemp -d)"
+readonly tmp_zip_dir="$(mktemp -d)/archive"
+mkdir "${tmp_zip_dir}"
+trap 'rm -rf "${progress_file}" "${name_file}" "${tmp_dir}" "${tmp_zip_dir}"' EXIT
 
 function notification {
   ./Notificator.app/Contents/Resources/Scripts/notificator --message "${1}" --title "${alfred_workflow_name}"
@@ -12,60 +17,56 @@ function ascii_basename {
 }
 
 function is_string_in_array {
-  local string="${1}"
+  local -r string="${1}"
 
   for value in "${@:2}"; do
     [[ "${string}" == "${value}" ]] && return 0
   done
+
   return 1
 }
 
 function transfer {
-  local tmp_zip_dir given_file tmp_dir dir_name zip_file file_path file_name hosts default_host upload_host
-
   # Consolidate files bit
-  # If acting on multiple files, first copy them to a directory
-  if [[ "${#}" -gt 1 ]]; then
-    readonly tmp_zip_dir="$(mktemp -d)/archive"
-    mkdir "${tmp_zip_dir}"
-    cp -R "${@}" "${tmp_zip_dir}"
-    readonly given_file="${tmp_zip_dir}"
+  # If acting on multiple files or a software bundle, first copy them to a directory
+  if [[ "${#}" -gt 1 || -d "${1}/Contents" ]]; then
+    cp -r "${@}" "${tmp_zip_dir}"
+    local -r given_file="${tmp_zip_dir}"
   else
-    readonly given_file="${1}"
+    local -r given_file="${1}"
   fi
 
   # Make zip if acting on a directory
   if [[ -d "${given_file}" ]]; then
-    readonly tmp_dir="$(mktemp -d)"
-    readonly dir_name="$(ascii_basename "${given_file}")"
-    readonly zip_file="${tmp_dir}/${dir_name}.zip"
+    local -r dir_name="$(ascii_basename "${given_file}")"
+    local -r zip_file="${tmp_dir}/${dir_name}.zip"
     DITTONORSRC=1 ditto -ck "${given_file}" "${zip_file}"
-    readonly file_path="${zip_file}"
+    local -r file_path="${zip_file}"
   else
-    readonly file_path="${given_file}"
+    local -r file_path="${given_file}"
   fi
 
   # Escape quotes, so we can quote curl's "--form"
   # to allow for filenames with commas and semicolons
-  readonly escaped_file_path="${file_path//\"/\\\"}"
+  local -r escaped_file_path="${file_path//\"/\\\"}"
 
   # Uploading bit
-  readonly file_name=$(ascii_basename "${file_path}")
+  local -r file_name=$(ascii_basename "${file_path}")
   echo -n "${file_name}" > "${name_file}"
   notification "Uploading “${file_name}”"
 
-  readonly hosts=('0x0.st' 'arxius.io' 'bayfiles.com' 'anonfile.com' 'megaupload.is' 'forumfiles.com')
-  readonly default_host="${hosts[0]}"
+  local -r hosts=('0x0.st' 'arxius.io' 'bayfiles.com' 'anonfile.com' 'megaupload.is' 'forumfiles.com')
+  local -r default_host="${hosts[0]}"
 
   if [[ -n "${upload_file_to}" ]]; then
     if is_string_in_array "${upload_file_to}" "${hosts[@]}"; then
-      readonly upload_host="${upload_file_to}"
+      local -r upload_host="${upload_file_to}"
     else
       echo "Invalid upload host: ${upload_file_to}" >&2
       exit 1
     fi
   else
-    readonly upload_host="${default_host}"
+    local -r upload_host="${default_host}"
   fi
 
   if [[ "${upload_host}" == '0x0.st' || "${upload_host}" == 'arxius.io' ]]; then
@@ -80,11 +81,9 @@ function transfer {
 }
 
 function kill_transfer {
-  local parent_process oldest_child_process
-
   # Kill parent to prevent notification showing success and child to stop upload
-  readonly parent_process="$(pgrep -f 'uploadfile upload')"
-  readonly oldest_child_process="$(pgrep -oP "${parent_process}")"
+  local -r parent_process="$(pgrep -f 'uploadfile upload')"
+  local -r oldest_child_process="$(pgrep -oP "${parent_process}")"
   kill "${parent_process}" "${oldest_child_process}"
 
   # Play sound and show message
@@ -101,6 +100,3 @@ else
   echo 'A wrong option was given.'
   exit 1
 fi
-
-# Delete temporary files
-rm "${progress_file}" "${name_file}"
