DownMedia: Updated _sharedresources

diff --git a/DownMedia/source/_sharedresources b/DownMedia/source/_sharedresources
--- a/DownMedia/source/_sharedresources
+++ b/DownMedia/source/_sharedresources
@@ -2,22 +2,23 @@
 
 readonly valid_resources=('blueutil' 'cpulimit' 'exiftool' 'ffmpeg' 'mediainfo' 'trash' 'youtubedl') # Keep in sync with resource functions
 readonly shared_resources_id='com.vitorgalvao.alfred._sharedresources'
-[[ -z "${alfred_workflow_data}" ]] && alfred_workflow_data="$(mktemp -d)/Workflow Data/fake_workflow" # To prevent commands reliant on this variable from breaking when testing outside a Workflow
+[[ -z "${alfred_workflow_data}" ]] && readonly alfred_workflow_data="$(mktemp -d)/Workflow Data/fake_workflow" # To prevent commands reliant on this variable from breaking when testing outside a Workflow
 readonly shared_resources_dir="$(dirname "${alfred_workflow_data}")/${shared_resources_id}"
 readonly shared_resources_bin="${shared_resources_dir}/bin"
 readonly PATH=/usr/local/bin:"${shared_resources_bin}":"${PATH}"
 
-function wrong_usage {
-  echo "
-    Could not recognise argument. It needs to be one or more of:
-      $(printf "\n  %s" "${valid_resources[@]}")
-  " | sed -E 's/^ {4}//' >&2
+function is_string_in_array {
+  local -r string="${1}"
 
-  exit 1
+  for value in "${@:2}"; do
+    [[ "${string}" == "${value}" ]] && return 0
+  done
+
+  return 1
 }
 
 function curl_error {
-  echo 'Could not download resource.' >&2
+  echo "Could not download ${1}." >&2
   exit 1
 }
 
@@ -26,22 +27,16 @@ function ensure_resources_dir {
 }
 
 function mount_dmg {
-  local dmg_path plist dicts mount_point
+  local -r dmg_path="${1}"
+  local -r plist="$(mktemp)" # We need to make the plist into a file so PlistBuddy will read it
 
-  readonly dmg_path="${1}"
-  readonly plist="$(mktemp)" # We need to make the plist into a file so PlistBuddy will read it
+  hdiutil mount -plist -nobrowse -readonly -mountrandom "$(mktemp -d)" "${dmg_path}" > "${plist}"
 
-  hdiutil mount -plist -nobrowse -readonly -mountrandom /tmp "${dmg_path}" > "${plist}"
+  local -r dicts="$(/usr/libexec/PlistBuddy -c 'print system-entities' "${plist}" | grep --count 'Dict')"
 
-  readonly dicts="$(/usr/libexec/PlistBuddy -c 'print system-entities' "${plist}" | grep --count 'Dict')"
   for i in $(seq 0 "$(bc <<< "${dicts} - 1")") ; do
-    mount_point="$(/usr/libexec/PlistBuddy -c "print system-entities:${i}:mount-point" "${plist}" 2>&1)"
-    if grep --quiet --invert-match 'Does Not Exist' <<< "${mount_point}"; then
-      break
-    fi
+    /usr/libexec/PlistBuddy -c "print system-entities:${i}:mount-point" "${plist}" 2>/dev/null
   done
-
-  echo -n "${mount_point}"
 }
 
 function unmount_dmg {
@@ -54,11 +49,9 @@ function blueutil_getter {
   blueutil_path="$(command -v 'blueutil')"
 
   if [[ -z "${blueutil_path}" ]]; then
-    local tar_extract blueutil_version
-
     blueutil_path="${shared_resources_bin}/blueutil"
-    readonly blueutil_version='2.5.1'
-    readonly tar_extract="$(mktemp -d)"
+    local -r blueutil_version='2.5.1'
+    local -r tar_extract="$(mktemp -d)"
 
     ensure_resources_dir
 
@@ -66,7 +59,7 @@ function blueutil_getter {
       mv "${tar_extract}/blueutil/${blueutil_version}/bin/blueutil" "${blueutil_path}"
       chmod +x "${blueutil_path}"
     else
-      curl_error
+      curl_error 'blueutil'
     fi
   fi
 }
@@ -76,11 +69,9 @@ function cpulimit_getter {
   cpulimit_path="$(command -v 'cpulimit')"
 
   if [[ -z "${cpulimit_path}" ]]; then
-    local tar_extract cpulimit_version
-
     cpulimit_path="${shared_resources_bin}/cpulimit"
-    readonly cpulimit_version='0.2'
-    readonly tar_extract="$(mktemp -d)"
+    local -r cpulimit_version='0.2'
+    local -r tar_extract="$(mktemp -d)"
 
     ensure_resources_dir
 
@@ -88,7 +79,7 @@ function cpulimit_getter {
       mv "${tar_extract}/cpulimit/${cpulimit_version}/bin/cpulimit" "${cpulimit_path}"
       chmod +x "${cpulimit_path}"
     else
-      curl_error
+      curl_error 'cpulimit'
     fi
   fi
 }
@@ -98,12 +89,10 @@ function exiftool_getter {
   exiftool_path="$(command -v 'exiftool')"
 
   function get_exiftool {
-    local tar_extract lib_dir latest_tag
-
     exiftool_path="${shared_resources_bin}/exiftool"
-    readonly tar_extract="$(mktemp -d)"
-    readonly lib_dir="${shared_resources_dir}/exiftool"
-    readonly latest_tag="$(curl --silent 'https://api.github.com/repos/exiftool/exiftool/tags' | grep 'tarball_url' | head -1 | sed -E 's/.*: "(.*)".*/\1/')"
+    local -r tar_extract="$(mktemp -d)"
+    local -r lib_dir="${shared_resources_dir}/exiftool"
+    local -r latest_tag="$(curl --silent 'https://api.github.com/repos/exiftool/exiftool/tags' | grep 'tarball_url' | head -1 | sed -E 's/.*: "(.*)".*/\1/')"
 
     ensure_resources_dir
 
@@ -111,7 +100,7 @@ function exiftool_getter {
       mv "${tar_extract}/"* "${lib_dir}"
       ln -s "${lib_dir}/exiftool" "${exiftool_path}"
     else
-      curl_error
+      curl_error 'exiftool'
     fi
   }
 
@@ -128,19 +117,17 @@ function ffmpeg_getter {
   ffmpeg_path="$(command -v 'ffmpeg')"
 
   function get_ffmpeg {
-    local download_page file_name dmg dmg_mount_point
-
     ffmpeg_path="${shared_resources_bin}/ffmpeg"
-    readonly download_page='https://evermeet.cx/pub/ffmpeg/'
-    readonly file_name="$(curl --silent "${download_page}" | grep '.dmg' | grep --invert-match '.sig' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
-    readonly dmg="$(mktemp)"
+    local -r download_page='https://evermeet.cx/pub/ffmpeg/'
+    local -r file_name="$(curl --silent "${download_page}" | grep '.dmg' | grep --invert-match '.sig' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
+    local -r dmg="$(mktemp)"
 
     if curl --silent --output "${dmg}" "${download_page}${file_name}"; then
-      readonly dmg_mount_point="$(mount_dmg "${dmg}")"
+      local -r dmg_mount_point="$(mount_dmg "${dmg}")"
       cp "${dmg_mount_point}/ffmpeg" "${ffmpeg_path}"
       unmount_dmg "${dmg_mount_point}"
     else
-      curl_error
+      curl_error 'ffmpeg'
     fi
   }
 
@@ -157,15 +144,13 @@ function mediainfo_getter {
   mediainfo_path="$(command -v 'mediainfo')"
 
   function get_mediainfo {
-    local file_name dmg pkg_extract dmg_mount_point
-
     mediainfo_path="${shared_resources_bin}/mediainfo"
-    readonly file_name="$(curl --silent 'https://mediaarea.net/en/MediaInfo/Download/Mac_OS' | grep 'CLI.*.dmg' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
-    readonly dmg="$(mktemp)"
-    readonly pkg_extract="$(mktemp -d)"
+    local -r file_name="$(curl --silent 'https://mediaarea.net/en/MediaInfo/Download/Mac_OS' | grep 'CLI.*.dmg' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
+    local -r dmg="$(mktemp)"
+    local -r pkg_extract="$(mktemp -d)"
 
     if curl --silent --output "${dmg}" "https:${file_name}"; then
-      readonly dmg_mount_point="$(mount_dmg "${dmg}")"
+      local -r dmg_mount_point="$(mount_dmg "${dmg}")"
       cd "${pkg_extract}" || exit 1
       xar -xf "${dmg_mount_point}/mediainfo.pkg"
       gunzip --decompress --stdout 'Payload' | cpio -i 2> /dev/null
@@ -173,7 +158,7 @@ function mediainfo_getter {
       unmount_dmg "${dmg_mount_point}"
       cd - > /dev/null || exit 1
     else
-      curl_error
+      curl_error 'mediainfo'
     fi
   }
 
@@ -190,11 +175,9 @@ function trash_getter {
   trash_path="$(command -v 'trash')"
 
   if [[ -z "${trash_path}" ]]; then
-    local tar_extract trash_version
-
     trash_path="${shared_resources_bin}/trash"
-    readonly trash_version='0.9.2'
-    readonly tar_extract="$(mktemp -d)"
+    local -r trash_version='0.9.2'
+    local -r tar_extract="$(mktemp -d)"
 
     ensure_resources_dir
 
@@ -202,7 +185,7 @@ function trash_getter {
       mv "${tar_extract}/trash/${trash_version}/bin/trash" "${trash_path}"
       chmod +x "${trash_path}"
     else
-      curl_error
+      curl_error 'trash'
     fi
   fi
 }
@@ -216,25 +199,32 @@ function youtubedl_getter {
   else
     ensure_resources_dir
     youtubedl_path="${shared_resources_bin}/youtube-dl"
+
     if curl --silent --location 'https://yt-dl.org/downloads/latest/youtube-dl' --output "${youtubedl_path}"; then
       chmod +x "${youtubedl_path}"
     else
-      curl_error
+      curl_error 'youtubedl'
     fi
   fi
 }
 
-resources_to_use=(${@})
-
-# Check if arguments are valid
-for rtu_index in "${!resources_to_use[@]}"; do
-  for vr_index in "${!valid_resources[@]}"; do
-    [[ "${resources_to_use[${rtu_index}]}" == "${valid_resources[${vr_index}]}" ]] && resource_is_valid='true' && break
-  done
-  [[ -n "${resource_is_valid}" ]] || wrong_usage
-  unset resource_is_valid
+for argv in "${@}"; do
+  resources_to_use+=("${argv}")
 done
 
+# Check if arguments are valid
+for resource in "${resources_to_use[@]}"; do
+  if ! is_string_in_array "${resource}" "${valid_resources[@]}"; then
+    echo "
+      Could not recognise argument ${1}. It needs to be one or more of:
+        $(printf "\n  %s" "${valid_resources[@]}")
+    " | sed -E 's/^ {6}//' >&2
+
+    exit 1
+  fi
+done
+
+# Get resources
 for resource in "${resources_to_use[@]}"; do
   "${resource}_getter" # Run the function to get the tool. '_getter' is required as otherwise the function will detect itself when running 'command'
 done
